spring.application.name=XRayBackend
server.port=8080

# Colab çal??t???nda Ngrok'tan alaca??n URL'i buraya yap??t?racaks?n:
# ÖRNEK: https://a1b2-c3d4.ngrok-free.app/predict
ai.service.url=https://unthrobbing-jana-freakish.ngrok-free.dev/predict

# Dosya boyutu limitleri (Röntgenler büyük olabilir)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB